version: 2.1

orbs:
    digitalocean: digitalocean/cli@0.1.1
    kubernetes: digitalocean/k8s@0.1.1
    awscli: circleci/aws-cli@2.0

workflows:
    production:
        jobs:
            - build:
                  context:
                      - blackblade
                  filters:
                      branches:
                          only:
                              - master
            - approve:
                  requires:
                      - build
                  type: approval
                  filters:
                      branches:
                          only:
                              - master
            - deploy:
                  requires:
                      - approve
                  context:
                      - blackblade
                  filters:
                      branches:
                          only:
                              - master
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                  name: 'Build & push images to Dockerhub'
                  command: |
                      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                      docker build -t brandonwade/blackblade-db:latest -t brandonwade/blackblade-db:$CIRCLE_SHA1 -f ./database/Dockerfile ./database
                      docker build -t brandonwade/blackblade-backup:latest -t brandonwade/blackblade-backup:$CIRCLE_SHA1 -f ./backup/Dockerfile ./backup
                      docker push brandonwade/blackblade-db:latest
                      docker push brandonwade/blackblade-db:$CIRCLE_SHA1
                      docker push brandonwade/blackblade-backup:latest
                      docker push brandonwade/blackblade-backup:$CIRCLE_SHA1
    deploy:
        executor: digitalocean/default
        steps:
            - checkout
            - kubernetes/install
            - kubernetes/initialize:
                  cluster: $DO_CLUSTER_NAME
            - awscli/setup
            - run:
                  name: 'Update Digital Ocean Space lifecycle rules'
                  command: |
                      aws s3api put-bucket-lifecycle-configuration --bucket=$DO_SPACE_NAME --lifecycle-configuration=file://backup/rules.json --endpoint=https://$DO_SPACE_ENDPOINT
            - run:
                  name: 'Set up Digital Ocean cluster configs'
                  command: |
                      doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID
            - run:
                  name: 'Update Kubernetes with the latest configs'
                  command: |
                      ./k8s.sh
            - run:
                  name: 'Update pods with the latest image versions'
                  command: |
                      kubectl set image deployments/db-deployment blackblade-db=brandonwade/blackblade-db:$CIRCLE_SHA1
                      kubectl set image cronjobs/backup-cronjob blackblade-backup=brandonwade/blackblade-backup:$CIRCLE_SHA1
