apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: backup-cronjob
spec:
    schedule: '0 1 */3 * *'
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - name: blackblade-backup
                          image: brandonwade/blackblade-backup:latest
                          env:
                              - name: ENVIRONMENT
                                valueFrom:
                                    secretKeyRef:
                                        name: environment
                                        key: ENVIRONMENT
                              - name: DB_USERNAME
                                valueFrom:
                                    secretKeyRef:
                                        name: mysqluser
                                        key: MYSQL_USER
                              - name: DB_PASSWORD
                                valueFrom:
                                    secretKeyRef:
                                        name: mysqlpassword
                                        key: MYSQL_PASSWORD
                              - name: DB_DATABASE
                                value: blackblade
                              - name: DB_HOST
                                valueFrom:
                                    secretKeyRef:
                                        name: dbhost
                                        key: DB_HOST
                              - name: DB_PORT
                                valueFrom:
                                    secretKeyRef:
                                        name: dbport
                                        key: DB_PORT
                              - name: DO_SPACE_NAME
                                valueFrom:
                                    secretKeyRef:
                                        name: dospacename
                                        key: DO_SPACE_NAME
                              - name: DO_SPACE_ENDPOINT
                                valueFrom:
                                    secretKeyRef:
                                        name: dospaceendpoint
                                        key: DO_SPACE_ENDPOINT
                              - name: AWS_ACCESS_KEY_ID
                                valueFrom:
                                    secretKeyRef:
                                        name: awsaccesskeyid
                                        key: AWS_ACCESS_KEY_ID
                              - name: AWS_SECRET_ACCESS_KEY
                                valueFrom:
                                    secretKeyRef:
                                        name: awssecretaccesskey
                                        key: AWS_SECRET_ACCESS_KEY
                    restartPolicy: OnFailure
                    imagePullSecrets:
                        - name: regcred
