kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ci
subjects:
    - kind: ServiceAccount
      name: ci
      namespace: default
roleRef:
    kind: ClusterRole
    name: ci
    apiGroup: rbac.authorization.k8s.io
