kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ci
rules:
    - apiGroups: ['', 'apps', 'batch', 'extensions', 'cert-manager.io']
      resources: ['deployments', 'services', 'replicasets', 'pods', 'jobs', 'cronjobs', 'certificates', 'ingresses', 'clusterissuers']
      verbs: ['*']
