kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ci
    namespace: default
subjects:
    - kind: ServiceAccount
      name: ci
      namespace: default
roleRef:
    kind: Role
    name: ci
    apiGroup: rbac.authorization.k8s.io
