kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: ci
    namespace: default
rules:
    - apiGroups: ['', 'apps', 'batch', 'extensions']
      resources: ['deployments', 'services', 'replicasets', 'pods', 'jobs', 'cronjobs', 'certificates']
      verbs: ['*']
